import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Providers } from "./providers";
import Header from "@/components/Header";

const font = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
          <Header />
          <div className="max-w-[90ch] mx-auto">
            <main className="mx-16">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
